manifest:
  projects:
    - name: zmk
      url: https://github.com/xingrz/zmk.git
      revision: zmkx-rel-20251223
      clone-depth: 10
      import:
        file: app/west.yml
        name-allowlist:
          - cmsis
          - cmsis-dsp
          - segger
          - hal_stm32
          - lvgl
          - nanopb
          - picolibc
          - zephyr
          - zmk-studio-messages
  self:
    path: config
